CREATE OR REPLACE MODEL
  `nida-crm-308203.Supermarket.supermarket-cluster` OPTIONS(model_type='kmeans',
    num_clusters=3 ) AS (
  SELECT
    COUNT(DISTINCT BASKET_ID) AS TOTAL_VISIT,
    SUM(SPEND) AS TOTAL_SPEND,
    AVG(SPEND) AS AVERAGE_TICKET_SIZE,
    STDDEV_POP(SPEND) AS STD_TICKET_SIZE,
    MAX(AGE) AS DURING_SINCE_FIRST_PURCHASE,
    MIN(AGE) AS DURING_SINCE_LAST_PURCHASE,
    MAX(AGE) - MIN(AGE) AS LENGHT_OF_STAY,
    (MAX(AGE) - MIN(AGE)) / COUNT(DISTINCT basket_id) AS AVERAGE_TIME_TO_EVENT
  FROM (
    SELECT
      CUST_CODE,
      BASKET_ID,
      SPEND,
      DATE_DIFF (DATE'2008-07-06', PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)), DAY) AS AGE
    FROM
      `nida-crm-308203.Supermarket.supermarket` )
  WHERE
    CUST_CODE IS NOT NULL
  GROUP BY
    CUST_CODE )