SELECT
    CURRENT_YEAR_MONTH,
    SUM(CASE WHEN CUSTOMER_TYPE = 'NEW' THEN 1 ELSE 0 END) AS `NEW_CUSTOMER`,
    SUM(CASE WHEN CUSTOMER_TYPE = 'REPEAT' THEN 1 ELSE 0 END) AS `REPEAT_CUSTOMER`,
    SUM(CASE WHEN CUSTOMER_TYPE = 'REACTIVATE' THEN 1 ELSE 0 END) AS `REACTIVATE_CUSTOMER`,
    SUM(CASE WHEN CUSTOMER_TYPE = 'REPEAT' THEN 1 ELSE 0 END) - LAG(COUNT(CURRENT_YEAR_MONTH), 1) OVER (ORDER BY CURRENT_YEAR_MONTH) AS `CHURN_CUSTOMER`,
FROM 
(
    SELECT
        CURRENT_YEAR_MONTH,
        CASE 
            WHEN PREVIOUS_YEAR_MONTH IS NULL THEN "NEW"
            WHEN (CURRENT_YEAR - PREVIOUS_YEAR) * 12 + (CURRENT_MONTH - PREVIOUS_MONTH) = 1 THEN "REPEAT"
            WHEN (CURRENT_YEAR - PREVIOUS_YEAR) * 12 + (CURRENT_MONTH - PREVIOUS_MONTH) > 1 THEN "REACTIVATE"
            WHEN PREVIOUS_YEAR_MONTH IS NOT NULL AND CURRENT_YEAR_MONTH IS NULL THEN "CHURN" 
        END AS CUSTOMER_TYPE
    FROM 
    (
        SELECT 
            CUST_CODE,
            SHOP_YEAR_MONTH AS CURRENT_YEAR_MONTH,
            LAG (SHOP_YEAR_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_YEAR_MONTH) AS PREVIOUS_YEAR_MONTH,
            CAST(FORMAT_DATETIME('%Y', PARSE_DATE('%Y%m', CAST(SHOP_YEAR_MONTH AS STRING))) AS INT64) AS CURRENT_YEAR,
            CAST(FORMAT_DATETIME('%m', PARSE_DATE('%Y%m', CAST(SHOP_YEAR_MONTH AS STRING))) AS INT64) AS CURRENT_MONTH,
            CAST(FORMAT_DATETIME('%Y', PARSE_DATE('%Y%m', LAG (SHOP_YEAR_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_YEAR_MONTH))) AS INT64) AS PREVIOUS_YEAR,
            CAST(FORMAT_DATETIME('%m', PARSE_DATE('%Y%m', LAG (SHOP_YEAR_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_YEAR_MONTH))) AS INT64) AS PREVIOUS_MONTH,
        FROM 
        (
            SELECT 
                CUST_CODE,
                FORMAT_DATETIME('%Y%m', PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS SHOP_YEAR_MONTH,
            FROM `nida-crm-308203.Supermarket.supermarket`
            WHERE CUST_CODE IS NOT NULL
            GROUP BY CUST_CODE, SHOP_YEAR_MONTH
        )
        ORDER BY CUST_CODE, SHOP_YEAR_MONTH
    )
    ORDER BY CURRENT_YEAR_MONTH
) 
GROUP BY CURRENT_YEAR_MONTH 
ORDER BY CURRENT_YEAR_MONTH